## Pseudolikelihood (finally)

In [6]:
import numpy as np

In [72]:
samples = np.array(samples)

In [3]:
from coniii import define_ising_helper_functions
calc_e, calc_observables, mchApproximation = define_ising_helper_functions()

In [21]:
sub_to_ind(9, 0, 1000)

999

In [51]:
samples.shape[0]

810

get_multipliers_r just gets all the Jij elements that have at least one i, j = r. It's symmetric so u only gotta do it once. args is a list and kwargs is a dictionary

In [52]:
get_multipliers_r, get_observables_r = define_pseudo_ising_helper_functions(9)

In [44]:
get_multipliers_r(0, multipliers)

(array([ 0.      ,  0.40352 ,  0.31349 ,  0.37752 , -0.027277,  0.21158 ,
        -0.30625 , -0.23198 ,  0.24388 ]), [0, 9, 10, 11, 12, 13, 14, 15, 16])

In [48]:
np.shape(samples)

(810, 9)

In [81]:


    def get_multipliers_r(r, multipliers, N=N):
        """Return r's field and all couplings to spin r.
        Parameters
        ----------a
        r : int
        multipliers : ndarray
            All fields and couplings concatenated together.
        Returns
        -------
        ndarray
            Relevant multipliers.
        list
            Index of where multipliers appear in full multipliers array.
        """
        
        ix = [r] 
        multipliersr = np.zeros(N)
        multipliersr[0] = multipliers[r]

        ixcounter = 1
        for i in range(N):
            if i!=r:
                if i<r:
                    ix.append( sub_to_ind(N, i, r) + N )
                    multipliersr[ixcounter] = multipliers[ix[ixcounter]]
                else:
                    ix.append( sub_to_ind(N, r, i) + N )
                    multipliersr[ixcounter] = multipliers[ix[ixcounter]]
                ixcounter += 1
        return multipliersr, ix


    def calc_observables_r(r, X, N=N):
        """Return the observables relevant for calculating the conditional probability of
        spin r.
        Parameters
        ----------
        r : int
            Spin index.
        X : ndarray
            Data samples of dimensions (n_samples, n_dim).
        Returns
        -------
        ndarray
            observables
        """

        obs = np.zeros((X.shape[0],N))
        for rowix in range(X.shape[0]):
            ixcounter = 1
            obs[rowix,0] = X[rowix,r]
            
            for i in range(N-1):
                for j in range(i+1,N):
                    if i==r or j==r:
                        obs[rowix,ixcounter] = X[rowix,i]*X[rowix,j]
                        ixcounter += 1
        return obs

    return get_multipliers_r, calc_observables_r 


(<function __main__.async-def-wrapper.<locals>.get_multipliers_r(r, multipliers, N=9)>,
 <function __main__.async-def-wrapper.<locals>.calc_observables_r(r, X, N=9)>)

In [82]:
A=calc_observables_r(0, samples)

In [85]:
samples[0]

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [83]:
A

array([[ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [-1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1., -1., -1., ..., -1., -1., -1.],
       ...,
       [ 1.,  1.,  1., ..., -1., -1., -1.],
       [-1.,  1.,  1., ...,  1.,  1.,  1.],
       [-1., -1., -1., ...,  1., -1.,  1.]])

In [78]:
len(A[0])

9